### ISSUE TITLE
Yamaha TG100 SysEx Dump Not Being Received Correctly

### ISSUE THREAD

**Issue by LackofTrack** [tyan0/hairless-midiserial#1]
Hi! This program works beautifully for my Roland SC-88 Pro but it has an issue receiving a SysEx Dump from my Yamaha TG100. The original program works correctly but this one has trouble with it. I've attached what the dump should look like and what this program outputs instead. While receiving the dump the program continuously outputs the message "Warning: got a status byte when we were expecting 65535 more data bytes, sending possibly incomplete MIDI message 0xf0". I've tried turning off Multiport and Hardware Flow Control and neither made a difference. Do you have any idea what the problem could be? 
Thank you and take care.
[Correct.txt](https://github.com/tyan0/hairless-midiserial/files/7858537/Correct.txt)
[Wrong.txt](https://github.com/tyan0/hairless-midiserial/files/7858538/Wrong.txt)

**Comment by tyan0** [comment]
Thanks for the report. I can confirm the problem with YAMAHA MU80. I will look into the problem.
Sorry for the late response. I did not notice your report.

**Comment by tyan0** [comment]
I found the cause. This is due to the [problem of foreach](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90617) with Qt4 and gcc version 9 or later. A countermeasure version has been uploaded. Could you please re-download it from https://github.com/tyan0/hairless-midiserial/releases/tag/mod7 and try it?

**Comment by LackofTrack** [comment]
The new build works perfectly! Thank you very much for your help. I will close the issue.

**Comment by tyan0** [comment]
Thanks for testing!
