### ISSUE TITLE
BigSur binary behaving very differently from Windows version

### ISSUE THREAD

**Issue by adriantaylor** [tyan0/hairless-midiserial#3]
I'm running 0.4-mod8 on both BigSur and Windows. I spent a LOT of time trying to debug my arduino code, because I just get it to give me anything other than Clock messages, despite only having note on/off in the code. Thought I'd give the windows version a try just to eliminate my stupidity, and it worked straight away, note on/off as designed.

**Comment by tyan0** [comment]
Thanks for the report. Could you please provide the messages which you don't expect?
Or, do you mean that note On/Off messages were not sent to Arduino?

**Comment by adriantaylor** [comment]
Of course, sorry - I was going to upload screenshots last night, but ran out of time.

Same board, same code (i.e. I have simply plugged it into Windows, tested, then plugged into Mac, tested, without any code changes or re-uploading to the board). 

Mac:
<img width="603" alt="Screenshot 2023-05-29 at 07 23 06" src="https://github.com/tyan0/hairless-midiserial/assets/6911389/1fdfc8ad-e877-4c3f-93cf-eee903d322c1">

Windows:
![Screenshot 2023-05-29 071920](https://github.com/tyan0/hairless-midiserial/assets/6911389/9b1e526e-0c60-49a1-8503-f53e1ead24ce)

**Comment by tyan0** [comment]
Have you set the baud rate etc. appropriately via File->Preferences menu?

**Comment by adriantaylor** [comment]
argh, thought I had, but it has not persisted. thanks and sorry!
